# ANÁLISIS EXPLORATORIO DE DATOS

In [1]:
import kagglehub
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

c:\Users\Usuario\miniconda3\envs\env_commerce_py313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Definición del problema
> - Recopilar los datos de ventas para visualizar compradores en potencia y los productos que mejor se venden.

## Recopilación de datos

In [2]:
# Download latest version
path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Usuario\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2

In [7]:
df_customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")
df_geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")
df_order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
df_order_payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
df_order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
df_orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")
df_products = pd.read_csv("../data/raw/olist_products_dataset.csv")
df_sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")
df_product_category_name_translation = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [24]:
df_orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [25]:
df_customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [ ]:
# Unir Órdenes con Clientes
df_master = pd.merge(df_orders, df_customers, on="customer_id", how="left")

In [26]:
df_order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [ ]:
# Unir con los Ítems 
df_master = pd.merge(df_master, df_order_items, on="order_id", how="left")

In [27]:
df_products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [ ]:
# Unir con Productos
df_master = pd.merge(df_master, df_products, on="product_id", how="left")

# Traducir las categorías (Para que sea legible)
df_master = pd.merge(df_master, df_product_category_name_translation, on="product_category_name", how="left")

In [ ]:
df_order_payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [45]:
df_master = pd.merge(df_master, df_order_payments, on="order_id", how="left")

In [46]:
df_master.head(15)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,8.0,13.0,9350.0,maua,SP,housewares,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,8.0,13.0,9350.0,maua,SP,housewares,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,8.0,13.0,9350.0,maua,SP,housewares,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,13.0,19.0,31570.0,belo horizonte,SP,perfumery,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,19.0,21.0,14840.0,guariba,SP,auto,1.0,credit_card,3.0,179.12
5,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,...,10.0,20.0,31842.0,belo horizonte,MG,pet_shop,1.0,credit_card,1.0,72.20
6,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,15.0,15.0,8752.0,mogi das cruzes,SP,stationery,1.0,credit_card,1.0,28.62
7,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00,80bb27c7c16e8f973207a5086ab329e2,86320,...,10.0,65.0,7112.0,guarulhos,SP,auto,1.0,credit_card,6.0,175.26
8,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00,36edbb3fb164b1f16485364b6fb04c73,98900,...,35.0,15.0,5455.0,sao paulo,SP,NaN,1.0,credit_card,1.0,65.95
9,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00,932afa1e708222e5821dac9cd5db4cae,26525,...,16.0,17.0,12940.0,atibaia,SP,auto,1.0,credit_card,3.0,75.16
10,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00,39382392765b6dc74812866ee5ee92a7,99655,...,35.0,15.0,13720.0,sao jose do rio pardo,SP,furniture_decor,1.0,boleto,1.0,35.95
11,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00,299905e3934e9e181bfb2e164dd4b4f8,18075,...,41.0,42.0,8577.0,itaquaquecetuba,SP,office_furniture,2.0,voucher,1.0,161.42
12,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00,299905e3934e9e181bfb2e164dd4b4f8,18075,...,41.0,42.0,8577.0,itaquaquecetuba,SP,office_furniture,1.0,credit_card,1.0,8.34
13,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00,f2a85dec752b8517b5e58a06ff3cd937,20780,...,12.0,39.0,29156.0,cariacica,ES,garden_tools,1.0,credit_card,1.0,259.06
14,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00,f2a85dec752b8517b5e58a06ff3cd937,20780,...,12.0,39.0,29156.0,cariacica,ES,garden_tools,1.0,credit_card,1.0,259.06

## Análisis descriptivo

In [47]:
df_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 118434 entries, 0 to 118433
Data columns (total 34 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118434 non-null  str
 1   customer_id                    118434 non-null  str
 2   order_status                   118434 non-null  str
 3   order_purchase_timestamp       118434 non-null  str
 4   order_approved_at              118258 non-null  str
 5   order_delivered_carrier_date   116360 non-null  str
 6   order_delivered_customer_date  115037 non-null  str
 7   order_estimated_delivery_date  118434 non-null  str
 8   customer_unique_id             118434 non-null  str
 9   customer_zip_code_prefix       118434 non-null  int64
 10  customer_city                  118434 non-null  str
 11  customer_state                 118434 non-null  str
 12  order_item_id                  117604 non-null  float64
 13  product_id                     117604 non-null  str
 14  seller_id                      117604 non-null  str
 15  shipping_limit_date            117604 non-null  str
 16  price                          117604 non-null  float64
 17  freight_value                  117604 non-null  float64
 18  product_category_name          115906 non-null  str
 19  product_name_lenght            115906 non-null  float64
 20  product_description_lenght     115906 non-null  float64
 21  product_photos_qty             115906 non-null  float64
 22  product_weight_g               117584 non-null  float64
 23  product_length_cm              117584 non-null  float64
 24  product_height_cm              117584 non-null  float64
 25  product_width_cm               117584 non-null  float64
 26  seller_zip_code_prefix         117604 non-null  float64
 27  seller_city                    117604 non-null  str
 28  seller_state                   117604 non-null  str
 29  product_category_name_english  115881 non-null  str
 30  payment_sequential             118431 non-null  float64
 31  payment_type                   118431 non-null  str
 32  payment_installments           118431 non-null  float64
 33  payment_value                  118431 non-null  float64
dtypes: float64(14), int64(1), str(19)
memory usage: 30.7 MB

## Limpieza de datos

In [48]:
df_master.duplicated().sum()

np.int64(0)

In [49]:
df_master.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'product_category_name_english', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [ ]:
df_master.drop(["order_status", "order_approved_at", "order_delivered_carrier_date", "order_estimated_delivery_date", "customer_zip_code_prefix", "customer_city",
                "customer_state", "seller_id", "shipping_limit_date", "freight_value", "product_category_name", "product_name_lenght", 
                "product_description_lenght", "product_photos_qty", "product_weight_g", "product_length_cm", "product_height_cm",
                "product_width_cm", "seller_zip_code_prefix", "seller_city", "seller_state", "payment_sequential", "payment_type", "payment_installments"], axis=1, inplace=True)

In [67]:
df_master["payment_value"].value_counts()

payment_value
50.00      351
100.00     300
20.00      286
77.57      250
35.00      166
          ...
1013.59      1
397.04       1
206.20       1
173.63       1
271.01       1
Name: count, Length: 29077, dtype: int64

In [63]:
df_master

,order_id,customer_id,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,order_item_id,product_id,price,product_category_name_english,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,1.0,87285b34884572647811a353c7ac498a,29.99,housewares,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,1.0,87285b34884572647811a353c7ac498a,29.99,housewares,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,1.0,87285b34884572647811a353c7ac498a,29.99,housewares,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,1.0,595fac2a385ac33a80bd5114aec74eb8,118.70,perfumery,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,1.0,aa4383b373c6aca5d8797843e5594415,159.90,auto,179.12
...,...,...,...,...,...,...,...,...,...,...,...
118429,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,2018-02-06 12:58:58,2018-02-28 17:37:56,2018-03-02 00:00:00,da62f9e57a76d978d02ab5362c509660,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,174.90,baby,195.00
118430,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,2017-08-27 14:46:43,2017-09-21 11:24:17,2017-09-27 00:00:00,737520a9aad80b3fbbdad19b66b37b30,1.0,b80910977a37536adeddd63663f916ad,205.99,home_appliances_2,271.01
118431,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,computers_accessories,441.16
118432,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,computers_accessories,441.16
118433,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,2018-03-08 20:57:30,2018-03-16 13:08:30,2018-04-03 00:00:00,60350aa974b26ff12caad89e55993bd6,1.0,006619bbed68b000c8ba3f8725d5409e,68.50,health_beauty,86.86